### ISSUE TITLE
Can't compile on latest master commit

### ISSUE THREAD

**Issue by jasl** [w3f/ring-vrf#57] opened 2023-08-31 09:03 UTC
Because Substrate is dependent on this repo via git, Cargo update dependencies often touch git commits unexpectedly.
So I found the issue on my Substrate project, and then I found it's reproducible on the repo as well.

Rust version 1.71.1

```
warning: unused import: `Fr`
  --> bandersnatch_vrfs/src/ring.rs:17:44
   |
17 | use ark_ed_on_bls12_381_bandersnatch::{Fq, Fr, SWConfig, SWAffine};
   |                                            ^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused imports: `HashToCurveError`, `curve_maps`, `map_to_curve_hasher::MapToCurveBasedHasher`
  --> bandersnatch_vrfs/src/lib.rs:14:15
   |
14 |     hashing::{HashToCurveError, curve_maps, map_to_curve_hasher::MapToCurveBasedHasher}, // HashToCurve
   |               ^^^^^^^^^^^^^^^^  ^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused imports: `Zero`, `borrow::BorrowMut`
  --> bandersnatch_vrfs/src/lib.rs:16:15
   |
16 | use ark_std::{borrow::BorrowMut, Zero, vec::Vec, rand::RngCore};   // io::{Read, Write}
   |               ^^^^^^^^^^^^^^^^^  ^^^^

error[E0061]: this function takes 3 arguments but 2 arguments were supplied
  --> bandersnatch_vrfs/src/ring.rs:34:5
   |
34 |     PiopParams::setup(domain, &mut rng)
   |     ^^^^^^^^^^^^^^^^^------------------ an argument of type `ark_ec::short_weierstrass::Affine<BandersnatchConfig>` is missing
   |
note: expected `Affine<BandersnatchConfig>`, found `&mut ChaCha20Rng`
  --> bandersnatch_vrfs/src/ring.rs:34:31
   |
34 |     PiopParams::setup(domain, &mut rng)
   |                               ^^^^^^^^
   = note:         expected struct `ark_ec::short_weierstrass::Affine<BandersnatchConfig>`
           found mutable reference `&mut ChaCha20Rng`
note: associated function defined here
  --> /Users/jasl/.cargo/git/checkouts/ring-proof-e9e49c3c86c409a2/8657210/ring/src/piop/params.rs:31:12
   |
31 |     pub fn setup(domain: Domain<F>, h: Affine<Curve>, seed: Affine<Curve>) -> Self {
   |            ^^^^^
help: provide the argument
   |
34 |     PiopParams::setup(domain, /* ark_ec::short_weierstrass::Affine<BandersnatchConfig> */, /* ark_ec::short_weierstrass::Affine<BandersnatchConfig> */)
   |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

For more information about this error, try `rustc --explain E0061`.
warning: `bandersnatch_vrfs` (lib) generated 3 warnings
error: could not compile `bandersnatch_vrfs` (lib) due to previous error; 3 warnings emitted
warning: build failed, waiting for other jobs to finish...
```

**Comment by burdges** [comment] 2023-08-31 10:08
Can we point substrate to c86ebd4114d3165d05f9ce28c1d9e8d7a9a4e801 for now? 

I'll have flavors I could publish to crates.io this week, but then substrate would need to be updated to them.

**Comment by burdges** [comment] 2023-08-31 10:09
Or we can force push this repo back to that commit and branch off everything else?

**Comment by burdges** [comment] 2023-08-31 10:27
I've fixed it in https://github.com/w3f/ring-vrf/commit/48b8507e2896e399172d7e3fe07fa63d2f9eea57

Arkworks inherited zcash's usage of std::io for serialization, but they wanted to be no_std, so they created ark_std::io.  This was necessary because rust-lang avoided doing a core::io for silly reasons.  This strategic mistake by rust-lang is also why scale exists.

It's likely these errors were caused by the tests using one flavor when run from the repo root, but another flavor when run from the crate itself.  

Anyways please reopen if this does not fix the problem.

**Comment by swasilyev** [comment] 2023-08-31 11:20
Ups, sorry! Just merged https://github.com/w3f/ring-proof/pull/10 blindly

**Comment by jasl** [comment] 2023-08-31 12:39
> Ups, sorry! Just merged [w3f/ring-proof#10](https://github.com/w3f/ring-proof/pull/10) blindly

Yeah, It seems this is the root cause

**Closed** 2023-08-31 13:45 UTC

**Comment by jasl** [comment] 2023-08-31 15:33
@swasilyev @burdges 

Currently, Substrate depends on an earlier version, which doesn't pin the ring-proof commit, and when I try to update Substrate, Cargo always updates ring-proof to the latest commit.

I tried to update the Substrate side, but it made massive dependencies conflicts.

To workaround, I manually edit ring-proof rev in Cargo.lock, I think the better way is release this repo to crates.io

**Comment by jasl** [comment] 2023-08-31 15:39
BTW, The problem is https://github.com/paritytech/ark-substrate/blob/main/curves/bls12_377/Cargo.toml#L21
sp-curve-bls12-377 depends on `ark-scale 0.0.3` but here depends on 0.0.10

**Comment by davxy** [comment] 2023-08-31 17:59
I updated the ref in our repo. 
As @jasl said `sp-ark-...` and co. depends on `ark-scale 0.0.3` but the fix is enough to unlock the situation...
BTW I'll update the dependencies there as well

**Comment by burdges** [comment] 2023-08-31 18:50
ark-scale 0.0.10 should be fairly stable I think.  

Afaik we've not yet started using ark-substrate yet internally, but we'll need to do so soon, so it's great to sort this out.

**Comment by davxy** [comment] 2023-09-01 10:32
Fixed by https://github.com/paritytech/polkadot-sdk/pull/1342
